services:
  db:
    container_name: cspi_db
    image: mariadb:latest
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=1G
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: $BD_NAME
      MYSQL_USER: $BD_PASSWORD_USER
      MYSQL_PASSWORD: $BD_PASSWORD_ROOT
      MYSQL_ROOT_PASSWORD: $BD_PASSWORD_ROOT
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - cspi_db:/var/lib/mysql
    ports:
      - "$PORT_MYSQL:3306"
    networks:
      - default
  cspi:
    container_name: cspi_amazon_linux
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - ./web:/var/www/central-de-soldaduras
    image: cspi_amazon_linux
    build:
      context: .
      dockerfile: Dockerfile
      args:
        XDEBUG_VERSION: $XDEBUG_VERSION
        DRUSH_VERSION: $DRUSH_VERSION
        PHP_VERSION: $PHP_VERSION
    privileged: true
    ports:
      - "$PORT_HTTP_HOST:80"
      - "$PORT_HTTPS_HOST:443"
    networks:
      - default
    dns:
      - "8.8.8.8"
      - "1.1.1.1"
    # command: /usr/sbin/init && systemctl restart php-fpm.service && systemctl restart nginx.service && cd /usr/share/nginx/html 
    command: bash -c "service nginx start && service php8.2-fpm start && tail -f /dev/null"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # extra host for environment DEV local
      - "local.cspi:127.0.0.1"
    hostname: cspi
    domainname: cspi
    deploy:
      resources:
        limits:
          memory: $RAM_MAX
        reservations:
          memory: $RAM_RES